---
- include_tasks: debian.yml
  when: ansible_distribution == "Debian"
  static: no

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  static: no

- name: NGINX ROLE | Updating apt cache
  apt:
    update_cache: yes
  become: true

- name: NGINX ROLE | Installing NGINX
  apt:
    pkg: nginx
    state: latest
  become: true

- file:
    path: /etc/nginx/upstream
    state: directory
    mode: "u=rwx,go-rwx"
  become: true

- template:
   src: ../templates/nginx.conf.j2
   dest: /etc/nginx/nginx.conf
   owner: root
   group: root
   mode: 0644
   backup: yes
  become: true

- file:
    path: /etc/nginx/sites-available
    state: directory
    mode: "u=rwx,go-rwx"
  become: true

- file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: "u=rwx,go-rwx"
  become: true

- name: NGINX ROLE | Starting NGINX
  service:
    name: nginx
    state: started
  become: true

