---
- name: NGINX ROLE | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX ROLE | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/debian/ {{ debian_codename }} nginx"

- name: NGINX ROLE | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/debian/ {{ debian_codename }} nginx"

- name: NGINX ROLE | Updating apt cache
  apt:
    update_cache: yes

- name: NGINX ROLE | Installing NGINX
  apt:
    pkg: nginx-full
    state: latest

- template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: NGINX ROLE | Starting NGINX
  service:
    name: nginx
    state: started

- iptables:
   chain: INPUT
   protocol: tcp
   match: tcp
   destination_port: 80
   jump: ACCEPT
  become: yes

- iptables:
   chain: INPUT
   protocol: tcp
   match: tcp
   destination_port: 443
   jump: ACCEPT
  become: yes